[package]
name = "aoc-19"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3

[dependencies]
cached = "0.41.0"
memoize = "0.3.3"
rayon = "1.6.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
